### ISSUE TITLE
More detailed error when attempting re-use of GPDir

### ISSUE THREAD

**Issue by els0r** [els0r/goProbe#143]
Related to the issues/errors outlined in https://github.com/els0r/goProbe/pull/141: if the directory isn't open, make sure to communicate it properly.

**Comment by fako1024** [comment]
@els0r Frankly, I'm having trouble reproducing the exact crash we were seeing on your screen, and in a synthetic test skipping the second call to `New()` we added to avoid the crash doesn't trigger any crash (so it shouldn't be necessary from what I can see). This leads me to believe that it's not that particular change that fixed the issue but maybe rather a side effect (e.g. the fact that you added a variable for the current timestamp that before was in a tighter scope.

Do you by any chance still have the stack trace from the crash on your console and could post it here?

**Comment by fako1024** [comment]
Never mind, got it reproduced on my own DB using a similar query. All good!

**Comment by fako1024** [comment]
For the record: Crash trace on commit 865a64d:
```
./goQuery --logging.level=debug -d /tmp/db_out2 -f '28.6.18 23:00' -l '28.6.18 23:30:00' list eth0
ts=2023-08-05T12:30:56.305+02:00 level=debug msg="handling first directory" version=872abf81 dir=/tmp/db_out2/eth0/2018/06/1530144000
ts=2023-08-05T12:30:56.305+02:00 level=debug msg="subtracting surplus blocks before tfirst" version=872abf81 blocks=288 surplus=252
ts=2023-08-05T12:30:56.307+02:00 level=debug msg="handling last directory" version=872abf81 dir=/tmp/db_out2/eth0/2018/06/1530144000
ts=2023-08-05T12:30:56.308+02:00 level=debug msg="opening last directory" version=872abf81
ts=2023-08-05T12:30:56.308+02:00 level=debug msg="checking last timestamp" version=872abf81 last=1530230129
ts=2023-08-05T12:30:56.308+02:00 level=debug msg="subtracting surplus blocks after tlast" version=872abf81 last=1530230129 blocks=288 surplus=29 offset=259
panic: runtime error: index out of range [259] with length 0

goroutine 1 [running]:
github.com/els0r/goProbe/pkg/goDB/storage/gpfile.(*GPFile).ReadBlockAtIndex(0x4?, 0xc00030c1f0?)
	/home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/goDB/storage/gpfile/gpfile.go:136 +0x60d
github.com/els0r/goProbe/pkg/goDB/storage/gpfile.(*GPDir).ReadBlockAtIndex(0xc0005c01e0, 0x4, 0x0?)
	/home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/goDB/storage/gpfile/gpdir.go:212 +0x4d
github.com/els0r/goProbe/pkg/goDB.(*DBWorkManager).readMetadataAndEvaluate(0xc00031e570?, 0xc0005c01e0, 0xc0000b8bd0, {0xc00039a878, 0x1d, 0x2000?}, 0x103, 0xc000110e00, 0xbe8858)
	/home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/goDB/DBWorkManager.go:434 +0xbc5
github.com/els0r/goProbe/pkg/goDB.(*DBWorkManager).ReadMetadata(0xc0001bce40, 0x5b354c50, 0x5b355358)
	/home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/goDB/DBWorkManager.go:357 +0xa51
github.com/els0r/goProbe/cmd/goQuery/cmd.listInterfaces({0x7ffefaa49e00, 0xc}, {0xc000110d80, 0x1, 0x0?})
	/home/fako/Develop/go/src/github.com/els0r/goProbe/cmd/goQuery/cmd/list.go:103 +0x3cd
github.com/els0r/goProbe/cmd/goQuery/cmd.listInterfacesEntrypoint(0x10908a0?, {0xc000110d80, 0x1, 0x8})
	/home/fako/Develop/go/src/github.com/els0r/goProbe/cmd/goQuery/cmd/list.go:50 +0x4f
github.com/spf13/cobra.(*Command).execute(0x10908a0, {0xc0000a8460, 0x8, 0xe})
	/home/fako/Develop/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x1090b80)
	/home/fako/Develop/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/fako/Develop/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/els0r/goProbe/cmd/goQuery/cmd.Execute()
	/home/fako/Develop/go/src/github.com/els0r/goProbe/cmd/goQuery/cmd/root.go:55 +0x32
main.main()
	/home/fako/Develop/go/src/github.com/els0r/goProbe/cmd/goQuery/main.go:6 +0x17
```
