### ISSUE TITLE
Deadlock during shutdown when no traffic present on interface

### ISSUE THREAD

**Issue by fako1024** [els0r/goProbe#16]
It seems that there is some potential deadlock situation during shutdown when there is no traffic on an interface being monitored. When trying to stop the service / executing Ctrl-C when running interactively in a shell, goprobe simply stops when trying to deactivate the handle for said interface, emitting the deactivation message for all prior interfaces and then stalling. Killing the binary with a trace signal reveals this (this is on release 2.1.1, built and executed on debian):

`C=0x45bdb1 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0xa0fc80, 0x80, 0x0, 0x0, 0xc000000000, 0x7ffd5b06bc58, 0x0, 0x0, 0x7ffd5b06bc78, 0x40d9c2, ...)
        /home/fk/Develop/goProbe-2.1.1/go/src/runtime/sys_linux_amd64.s:531 +0x21
runtime.futexsleep(0xa0fc80, 0x7ffd00000000, 0xffffffffffffffff)
        /home/fk/Develop/goProbe-2.1.1/go/src/runtime/os_linux.go:46 +0x4b
runtime.notesleep(0xa0fc80)
        /home/fk/Develop/goProbe-2.1.1/go/src/runtime/lock_futex.go:151 +0xa2
runtime.stoplockedm()
        /home/fk/Develop/goProbe-2.1.1/go/src/runtime/proc.go:2165 +0x8a
runtime.schedule()
        /home/fk/Develop/goProbe-2.1.1/go/src/runtime/proc.go:2565 +0x2d9
runtime.park_m(0xc00006a600)
        /home/fk/Develop/goProbe-2.1.1/go/src/runtime/proc.go:2676 +0xae
runtime.mcall(0x5a43d0)
        /home/fk/Develop/goProbe-2.1.1/go/src/runtime/asm_amd64.s:299 +0x5b

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc00008a4e8)
        /home/fk/Develop/goProbe-2.1.1/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc00008a4e0)
        /home/fk/Develop/goProbe-2.1.1/go/src/sync/waitgroup.go:130 +0x64
OSAG/goProbe.(*RunGroup).Wait(0xc00008a4e0)
        /home/fk/Develop/goProbe-2.1.1/addon/gocode/src/OSAG/goProbe/rungroup.go:28 +0x2d
OSAG/goProbe.(*CaptureManager).disable(0xc00001e080, 0xc0000825e0, 0x2, 0x2)
        /home/fk/Develop/goProbe-2.1.1/addon/gocode/src/OSAG/goProbe/capture_manager.go:118 +0xfc
OSAG/goProbe.(*CaptureManager).DisableAll(0xc00001e080)
        /home/fk/Develop/goProbe-2.1.1/addon/gocode/src/OSAG/goProbe/capture_manager.go:169 +0x5f
main.main()
        /home/fk/Develop/goProbe-2.1.1/addon/gocode/src/OSAG/capture/cmd.go:211 +0x871

goroutine 19 [syscall]:
os/signal.signal_recv(0x6700e0)
        /home/fk/Develop/goProbe-2.1.1/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /home/fk/Develop/goProbe-2.1.1/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /home/fk/Develop/goProbe-2.1.1/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 4 [chan receive]:
main.handleWriteouts(0xc00005c060, 0xc000178000, 0x0)
        /home/fk/Develop/goProbe-2.1.1/addon/gocode/src/OSAG/capture/cmd.go:272 +0xef5
created by main.main
        /home/fk/Develop/goProbe-2.1.1/addon/gocode/src/OSAG/capture/cmd.go:186 +0x6e3

goroutine 21 [IO wait]:
internal/poll.runtime_pollWait(0x7f83ddf12e30, 0x72, 0x0)
        /home/fk/Develop/goProbe-2.1.1/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc00016c018, 0x72, 0xc000058000, 0x0, 0x0)
        /home/fk/Develop/goProbe-2.1.1/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc00016c018, 0xffffffffffffff00, 0x0, 0x0)
        /home/fk/Develop/goProbe-2.1.1/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc00016c000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/fk/Develop/goProbe-2.1.1/go/src/internal/poll/fd_unix.go:384 +0x1a0
net.(*netFD).accept(0xc00016c000, 0x0, 0xc0001780c0, 0xc000035fc8)
        /home/fk/Develop/goProbe-2.1.1/go/src/net/fd_unix.go:238 +0x42
net.(*UnixListener).accept(0xc000010030, 0x0, 0x0, 0x0)
        /home/fk/Develop/goProbe-2.1.1/go/src/net/unixsock_posix.go:162 +0x32
net.(*UnixListener).Accept(0xc000010030, 0xc000088300, 0xc00008a408, 0x66f5c0, 0xc0001780c0)
        /home/fk/Develop/goProbe-2.1.1/go/src/net/unixsock.go:257 +0x47
main.handleControlSocket(0x670fe0, 0xc000010030, 0xc00005c060)
        /home/fk/Develop/goProbe-2.1.1/addon/gocode/src/OSAG/capture/cmd.go:366 +0xc8
created by main.main
        /home/fk/Develop/goProbe-2.1.1/addon/gocode/src/OSAG/capture/cmd.go:197 +0x7f0

goroutine 7 [chan receive]:
OSAG/goProbe.(*Capture).process(0xc00016c200)
        /home/fk/Develop/goProbe-2.1.1/addon/gocode/src/OSAG/goProbe/capture.go:456 +0x2b6
created by OSAG/goProbe.NewCapture
        /home/fk/Develop/goProbe-2.1.1/addon/gocode/src/OSAG/goProbe/capture.go:365 +0x174

goroutine 9 [syscall]:
github.com/google/gopacket/pcap._Cfunc_pcap_next_ex_escaping(0x7f83c4000a10, 0xc00016e310, 0xc00016e318, 0x0)
        _cgo_gotypes.go:538 +0x4d
github.com/google/gopacket/pcap.(*Handle).getNextBufPtrLocked.func1(0x7f83c4000a10, 0xc00016e310, 0xc00016e318, 0xc00001e4f0)
        /home/fk/Develop/goProbe-2.1.1/addon/gocode/src/github.com/google/gopacket/pcap/pcap.go:403 +0x6a
github.com/google/gopacket/pcap.(*Handle).getNextBufPtrLocked(0xc00016e2d0, 0xc000040d20, 0x3, 0xc000020070)
        /home/fk/Develop/goProbe-2.1.1/addon/gocode/src/github.com/google/gopacket/pcap/pcap.go:403 +0x8a
github.com/google/gopacket/pcap.(*Handle).ReadPacketData(0xc00016e2d0, 0x647c68, 0x0, 0xc000040d30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/fk/Develop/goProbe-2.1.1/addon/gocode/src/github.com/google/gopacket/pcap/pcap.go:340 +0x77
github.com/google/gopacket.(*PacketSource).NextPacket(0xc0000103c0, 0x646f98, 0xc00016c280, 0xc000040f10, 0x0)
        /home/fk/Develop/goProbe-2.1.1/addon/gocode/src/github.com/google/gopacket/packet.go:801 +0x6d
OSAG/goProbe.(*Capture).process.func1(0x0, 0x0)
        /home/fk/Develop/goProbe-2.1.1/addon/gocode/src/OSAG/goProbe/capture.go:398 +0x99
OSAG/goProbe.(*Capture).process(0xc00016c280)
        /home/fk/Develop/goProbe-2.1.1/addon/gocode/src/OSAG/goProbe/capture.go:440 +0xd0
created by OSAG/goProbe.NewCapture
        /home/fk/Develop/goProbe-2.1.1/addon/gocode/src/OSAG/goProbe/capture.go:365 +0x174

goroutine 22 [chan receive]:
main.handleRotations(0xc00005c060)
        /home/fk/Develop/goProbe-2.1.1/addon/gocode/src/OSAG/capture/cmd.go:232 +0xb6
created by main.main
        /home/fk/Develop/goProbe-2.1.1/addon/gocode/src/OSAG/capture/cmd.go:200 +0x812

goroutine 25 [chan receive]:
OSAG/goProbe.(*Capture).Disable(0xc00016c280)
        /home/fk/Develop/goProbe-2.1.1/addon/gocode/src/OSAG/goProbe/capture.go:743 +0xdd
OSAG/goProbe.(*CaptureManager).disable.func1()
        /home/fk/Develop/goProbe-2.1.1/addon/gocode/src/OSAG/goProbe/capture_manager.go:115 +0x4a
OSAG/goProbe.(*RunGroup).Run.func1(0xc00008a4e0, 0xc000082620)
        /home/fk/Develop/goProbe-2.1.1/addon/gocode/src/OSAG/goProbe/rungroup.go:23 +0x4f
created by OSAG/goProbe.(*RunGroup).Run
        /home/fk/Develop/goProbe-2.1.1/addon/gocode/src/OSAG/goProbe/rungroup.go:21 +0x62

rax    0xca
rbx    0xa0fb40
rcx    0x45bdb3
rdx    0x0
rdi    0xa0fc80
rsi    0x80
rbp    0x7ffd5b06bc40
rsp    0x7ffd5b06bbf8
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xc
r13    0xff
r14    0x66a556
r15    0x0
rip    0x45bdb1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0` 

The issue is reproducible on any interface which encounters zero traffic (e.g. when no cable is connected and no outgoing connections are being established).
My first guess would be that the NextPacket() method is waiting for a new packet while the deactivation signal is received on the control channel, which cannot be executed due to the capture method still waiting...

**Comment by florianl** [comment]
maybe because of https://github.com/google/gopacket/issues/253 ?

**Comment by els0r** [comment]
This one's more serious than I though. Effectively breaking `systemctl` use of goProbe.

**Comment by fako1024** [comment]
@els0r I think systemd may actually be the solution to the issue here - as part of feature/debPackage I've added an explicit 30s timeout to the service definition which will kill the service in the rate situation that this occurs. I wouldn't say we should close the issue but I'll remove the critical flag for the moment...

**Comment by els0r** [comment]
Sounds good. Given that systemd takes care of the workaround, I’d say that we can release v4 after merging the debian branch and implementing /query for the goProbe API

**Comment by florianl** [comment]
in general, a reading operation on a socket is a blocking event. So if there is no traffic, this will block forever. However, since go 1.12 it is now possible to set `SetReadDeadline` and `SetWriteDeadline` on such sockets. But as far as I can tell, it is not implemented here.

**Comment by hxzhao527** [comment]
any progress about this problem?

**Comment by fako1024** [comment]
I just tried looking into the issue again, however was unable to reproduce it on the current develop branch _or_ using the oldest available build I have available (from 2020). Both exit properly when running on interfaces that don't receive any traffic (I tried all kinds of combinations, with and without other active and inactive interfaces, to no avail). Systemd service interaction works normally in all these situations as well.

I assume that this was fixed implicitly somewhere along the road when we did all the rewrites. I'll close the issue for now, but should this pop up again (on a recent branch / release), please feel free to re-open it!
