### ISSUE TITLE
Build failure on x86 / ARM due to [various issues]

### ISSUE THREAD

**Issue by fako1024** [els0r/goProbe#204]
- When building goProbe on a non-64bit architecture it fails due to 'int' being used in a couple of places for `GPDir` handling (which is probably the worst place to be inconsistent about byte width of involved variables :roll_eyes:):

```
# github.com/els0r/goProbe/pkg/goDB/storage/gpfile
pkg/goDB/storage/gpfile/gpdir.go:372:20: maxUint32 (untyped int constant 4294967295) overflows int
# github.com/els0r/goProbe/pkg/goDB/storage/gpfile [github.com/els0r/goProbe/cmd/goProbe]
pkg/goDB/storage/gpfile/gpdir.go:372:20: maxUint32 (untyped int constant 4294967295) overflows int
# github.com/els0r/goProbe/pkg/goDB/storage/gpfile [github.com/els0r/goProbe/cmd/goQuery]
pkg/goDB/storage/gpfile/gpdir.go:372:20: maxUint32 (untyped int constant 4294967295) overflows int
# github.com/els0r/goProbe/pkg/goDB/storage/gpfile [github.com/els0r/goProbe/cmd/legacy]
pkg/goDB/storage/gpfile/gpdir.go:372:20: maxUint32 (untyped int constant 4294967295) overflows int
```
Since fixing this will involve changing some types for the metadata encoding, this is critical and must be handled as part of v4 to avoid breaking the serialization later on.

- ~Building goQuery fails due to a memory alignment issue on linker level (unfortunately that's not easy to trace since it's _the linker_ that panics :dizzy_face:)~ Luckilly, this was just an artifact due to me `rsync`ing between my dev host and the test Raspberry Pi. Issue was gone when forcing a `go build -a` :relieved:
```
# github.com/els0r/goProbe/cmd/goQuery
panic: bad alignment value

goroutine 1 [running]:
cmd/link/internal/loader.(*Loader).SetSymAlign(...)
	cmd/link/internal/loader/loader.go:1289
cmd/link/internal/loader.(*loadState).preloadSyms(0xc3d38c, 0x14288c0, 0x2)
	cmd/link/internal/loader/loader.go:2217 +0x670
cmd/link/internal/loader.(*Loader).LoadSyms(0xdfa000, 0x4a4bb8)
	cmd/link/internal/loader/loader.go:2249 +0x2b4
cmd/link/internal/ld.(*Link).loadlib(0xd0e000)
	cmd/link/internal/ld/lib.go:597 +0x4ec
cmd/link/internal/ld.Main(0x4a4bb8, {0x4, 0x8, 0x1, 0xd, 0xe, 0x1c00000, {0x0, 0x0, 0x0}, ...})
	cmd/link/internal/ld/main.go:280 +0x145c
main.main()
	cmd/link/main.go:72 +0xbd8
```

- There is an unaligned atomic counter operation in `DBWorkManager` (should be an easy fix along the lines of https://github.com/fako1024/slimcap/issues/69):
```
panic: unaligned 64-bit atomic operation

goroutine 12068 [running]:
runtime/internal/atomic.panicUnaligned()
	/usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Xadd64(0x22901c4, 0x1)
	/usr/local/go/src/runtime/internal/atomic/atomic_arm.s:258 +0x14
github.com/els0r/goProbe/pkg/goDB.(*DBWorkManager).grabAndProcessWorkload.func1()
	/root/Develop/goProbe/pkg/goDB/DBWorkManager.go:495 +0x2a8
created by github.com/els0r/goProbe/pkg/goDB.(*DBWorkManager).grabAndProcessWorkload in goroutine 12041
	/root/Develop/goProbe/pkg/goDB/DBWorkManager.go:457 +0xb8
FAIL	github.com/els0r/goProbe/pkg/e2etest	87.852s
```

- `query.WithNumResults()` uses a simple `int` (and a constant very large value outside the 32-bit range is used in the test suite for `goDB/engine`):
```
# github.com/els0r/goProbe/pkg/goDB/engine [github.com/els0r/goProbe/pkg/goDB/engine.test]
./benchmarks_test.go:996:25: cannot use 9999999999999999 (untyped int constant) as int value in argument to query.WithNumResults (overflows)
./benchmarks_test.go:1013:25: cannot use 9999999999999999 (untyped int constant) as int value in argument to query.WithNumResults (overflows)
./benchmarks_test.go:1030:25: cannot use 9999999999999999 (untyped int constant) as int value in argument to query.WithNumResults (overflows)
./benchmarks_test.go:1047:25: cannot use 9999999999999999 (untyped int constant) as int value in argument to query.WithNumResults (overflows)
./benchmarks_test.go:1064:25: cannot use 9999999999999999 (untyped int constant) as int value in argument to query.WithNumResults (overflows)
./benchmarks_test.go:1081:25: cannot use 9999999999999999 (untyped int constant) as int value in argument to query.WithNumResults (overflows)
./benchmarks_test.go:1098:25: cannot use 9999999999999999 (untyped int constant) as int value in argument to query.WithNumResults (overflows)
./benchmarks_test.go:1115:25: cannot use 9999999999999999 (untyped int constant) as int value in argument to query.WithNumResults (overflows)
./benchmarks_test.go:1132:25: cannot use 9999999999999999 (untyped int constant) as int value in argument to query.WithNumResults (overflows)
./benchmarks_test.go:1149:25: cannot use 9999999999999999 (untyped int constant) as int value in argument to query.WithNumResults (overflows)
./benchmarks_test.go:1149:25: too many errors
```

- Decompression via LZ4 causes random errors on ARM - I've tested cross-platform compression / decompression, and decompression on the ARM device always throws random errors such as:
```
ts=2023-09-07T13:22:30.204+01:00 level=warn msg="Failed to read column: lz4: decompression failed: ERROR_maxBlockSize_invalid (-2)" version=devel day="&{gpFiles:[0x3a7f3e0 <nil> <nil> <nil> <nil> <nil> <nil> <nil>] options:[0x2f21d4 0x2f6f5c] basePath:/tmp/db_out_local/eth0 dirPath:/tmp/db_out_local/eth0/2020/01/1579824000 metaPath:/tmp/db_out_local/eth0/2020/01/1579824000/.blockmeta accessMode:0 permissions:420 isOpen:true Metadata:0x2c747e0}" block=1579837788 column=sip
```
Sometimes it even crashes when performing the decompression. Compression seems to be fine (since decompressing a DB converted on the ARM device via the `legacy` tools works perfectly on an AMD64 device, just not vice versa).
In addition, the goDB test suite fails as well (so even when sticking to ARM it fails randomly). Unfortunately, running the encoder test suite all is fine, so maybe it's related to GPDir / GPFile.

DoD

- [x] Straighten out byte width of all variables involved in serialization
- [x] Fix goQuery link panic (yay)
- [x] Fix unaligned atomic counter
- [x] Fix type of `query.WithNumResults()` and regenerate tests
- [x] Fix ~LZ4 decompression~ `GPFile` memory buffer pool concurrency (ARM)
- [x] Build / run successfully on x86 / ARM system
- [x] Test cross-system access to DB

**Comment by fako1024** [comment]
@els0r For obvious reasons this is crucial, I'll work on it today (and hopefully fix it) :stuck_out_tongue:

**Comment by fako1024** [comment]
Turns out the decompression issues weren't decompression issues after all. instead, there seems to be some ARM-specific difference when handling the globally shared memory buffer pool for the "read-full" mode for `GPFile` instances (issue went away in low-memory mode, where we disable that). Solved by allocating one pool per worker instead of one per DBWorkManager (will not have any impact because the number of actual buffer elements will stay the same). Frankly, why this happens I have no clue, in theory it should be fully safe (and on AMD64 it seems to be)... :see_no_evil:
