### ISSUE TITLE
Panic during packet parsing

### ISSUE THREAD

**Issue by els0r** [els0r/goProbe#279]
Observed in production:

```
panic: runtime error: index out of range [20] with length 20

goroutine 138 [running]:
github.com/els0r/goProbe/pkg/capture.ParsePacket(...)
	/usr/src/packages/src/sdwan/security/pkg/OSAGtmi/goProbe/pkg/capture/flow.go:74
github.com/els0r/goProbe/pkg/capture.(*Capture).capturePacket(0xc000000780?)
	/usr/src/packages/src/sdwan/security/pkg/OSAGtmi/goProbe/pkg/capture/capture.go:346 +0x94c
github.com/els0r/goProbe/pkg/capture.(*Capture).process.func1()
	/usr/src/packages/src/sdwan/security/pkg/OSAGtmi/goProbe/pkg/capture/capture.go:314 +0x18a
created by github.com/els0r/goProbe/pkg/capture.(*Capture).process in goroutine 104
	/usr/src/packages/src/sdwan/security/pkg/OSAGtmi/goProbe/pkg/capture/capture.go:239 +0x96
```
Has to do with the bounds check for IPv4 header length:

```golang
		_ = ipLayer[ipv4.HeaderLen] // bounds check hint to compiler
```

DoD:

- [x] identify cause of bug
- [ ] fix
- [ ] reactivate goProbe on affected sensor host

**Comment by fako1024** [comment]
Must be related to the packet length, craps out upon compiler hint (i.e. apparently the slice is smaller than the IPv4 header length - which shouldn't happen by definition)...
```
_ = ipLayer[ipv4.HeaderLen] // bounds check hint to compiler
```

**Comment by fako1024** [comment]
This is actually caused by more or less invalid packets that stop immediately after the IPv4 header (IP protocol 248 is unassigned).
```
# tcpdump -ni any length = 20
tcpdump: data link type LINUX_SLL2
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on any, link-type LINUX_SLL2 (Linux cooked v2), snapshot length 262144 bytes
09:50:39.209108 eth1  Out IP 10.20.225.16 > 10.114.201.13:  ip-proto-249 0
09:50:39.209114 peth1 Out IP 10.20.225.16 > 10.114.201.13:  ip-proto-249 0
09:50:39.209113 nsm0  P   IP 10.20.225.16 > 10.114.201.13:  ip-proto-249 0
09:50:40.285010 eth1  Out IP 10.20.225.16 > 10.114.201.13:  ip-proto-248 0
09:50:40.285016 peth1 Out IP 10.20.225.16 > 10.114.201.13:  ip-proto-248 0
09:50:40.285014 nsm0  P   IP 10.20.225.16 > 10.114.201.13:  ip-proto-248 0
```

I'd even consider this a security vulnerability (because I assume that you can kill `goProbe` simply by sending a crafted packet over the wire...

Embarrassingly the reasons this isn't caught is because the slice addressing is plain wrong:
```
 ipLayer[ipv4.HeaderLen]
```
accesses one beyond the IPv4 header, so all of our checks we do before are useless in the case that the packet length is _exactly_ 20 (which is the case here). :see_no_evil:
