### ISSUE TITLE
Deadlock in three-point capture routine lock (sporadic)

### ISSUE THREAD

**Issue by fako1024** [els0r/goProbe#317]
For reasons unknown there seem to be some occurrences of a deadlock situation on very busy hosts (in particular with many interfaces), triggered by a failure of the main capture loop to confirm the lock request, leading to the `lock()` method to be stuck on the respective channel receive operation:
```
goroutine 423 [chan receive, 2493 minutes]:
github.com/els0r/goProbe/pkg/capture.(*Capture).lock(0xc0025cd790)
        /usr/src/packages/src/osco/observability/pkg/OSAGtmi/goProbe/pkg/capture/capture.go:591 +0xa5
github.com/els0r/goProbe/pkg/capture.(*Manager).rotate(0xc000622400, {0xf29f00, 0xc00004f400}, 0xc0017aa600, {0x0, 0x0, 0x0})
        /usr/src/packages/src/osco/observability/pkg/OSAGtmi/goProbe/pkg/capture/capture_manager.go:476 +0x1b1
github.com/els0r/goProbe/pkg/capture.(*Manager).performWriteout(0xc000622400, {0xf29f00, 0xc00004f400}, {0x0?, 0x1?, 0x155e8e0?}, {0x0, 0x0, 0x0})
        /usr/src/packages/src/osco/observability/pkg/OSAGtmi/goProbe/pkg/capture/capture_manager.go:541 +0xd8
github.com/els0r/goProbe/pkg/capture.(*Manager).ScheduleWriteouts.func1()
        /usr/src/packages/src/osco/observability/pkg/OSAGtmi/goProbe/pkg/capture/capture_manager.go:156 +0x285
created by github.com/els0r/goProbe/pkg/capture.(*Manager).ScheduleWriteouts in goroutine 1
        /usr/src/packages/src/osco/observability/pkg/OSAGtmi/goProbe/pkg/capture/capture_manager.go:127 +0x86
```
Since at that point the method has already acquired the global buffer from the single-element memory pool (which is by design) all other methods trying to establish a lock fail to do so and hence everything is blocked (including global writeouts). At the same time, goroutines accumulate with each additional request using the `lock()` method.

DoD

- [x] Increase safety of three-point lock (graceful error handling?)
- [x] Ensure that `lock()` has some form of timeout to ensure we don't accumulate goroutines
- [x] Add some form of logging to ensure we are informed if such things happen

**Comment by fako1024** [comment]
I was also able to produce a different deadlock when trying to rapidly reconfigure goprobe on a local machine:
```
panic: unexpectedly failed to unblock capture handle, deadlock inevitable: cannot call Unblock() on nil / closed capture source

goroutine 56 [running]:
github.com/els0r/goProbe/pkg/capture.(*Capture).lock(0xc00017bd40)
	/home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture.go:587 +0xf9
github.com/els0r/goProbe/pkg/capture.(*Manager).rotate(0xc0005a8a00, {0xfeec80, 0xc000258900}, 0xc0000e1b00, {0x0, 0x0, 0x0})
	/home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture_manager.go:476 +0x1b1
github.com/els0r/goProbe/pkg/capture.(*Manager).performWriteout(0xc0005a8a00, {0xfeec80, 0xc000258900}, {0x0?, 0x1?, 0x1657400?}, {0x0, 0x0, 0x0})
	/home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture_manager.go:541 +0xd8
github.com/els0r/goProbe/pkg/capture.(*Manager).ScheduleWriteouts.func1()
	/home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture_manager.go:156 +0x285
created by github.com/els0r/goProbe/pkg/capture.(*Manager).ScheduleWriteouts in goroutine 1
	/home/fako/Develop/go/src/github.com/els0r/goProbe/pkg/capture/capture_manager.go:127 +0x86
```
