### ISSUE TITLE
goProbe panics when writing out data for an interface without flows

### ISSUE THREAD

**Issue by els0r** [els0r/goProbe#67]
```
ts=2023-03-06T17:04:46Z level=debug caller=capture/capture.go:183 msg="there are currently no flow records available" app_name=goProbe app_version=8e02f0a7 iface=eth1 state=capturing
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x751a17]

goroutine 9 [running]:
github.com/els0r/goProbe/pkg/goDB.dbData({0xc0001a2000?, 0x88?}, 0x0?, 0xc000121830?)
        /usr/src/packages/src/sdwan/security/pkg/OSAGtmi/goProbe/pkg/goDB/db_writer.go:107 +0xb7
github.com/els0r/goProbe/pkg/goDB.(*DBWriter).Write(0xc0002c2930, 0xc000121d60?, {0xc00002d540?}, 0x4?)
        /usr/src/packages/src/sdwan/security/pkg/OSAGtmi/goProbe/pkg/goDB/db_writer.go:57 +0x23d
github.com/els0r/goProbe/pkg/goprobe/writeout.(*Handler).HandleWriteouts.func1()
        /usr/src/packages/src/sdwan/security/pkg/OSAGtmi/goProbe/pkg/goprobe/writeout/handler.go:217 +0x790
created by github.com/els0r/goProbe/pkg/goprobe/writeout.(*Handler).HandleWriteouts
        /usr/src/packages/src/sdwan/security/pkg/OSAGtmi/goProbe/pkg/goprobe/writeout/handler.go:179 +0xaa
```

**Comment by fako1024** [comment]
Yeah, saw that already this morning. is already fixed locally. Didn't want to raise an extra issue, but thanks for reporting!

**Comment by fako1024** [comment]
@els0r See attached PR, feel free to merge at your discretion.
